version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: allocation
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '3308:3306'
